# Generated by Django 5.2.12 on 2026-03-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneaker',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
